// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "./internal/engine/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as task$0 from "./internal/task/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddTask adds a new download task
 */
export function AddTask(urlStr: string, dir: string, filename: string, maxConn: number): $CancellablePromise<task$0.Task | null> {
    return $Call.ByID(571013529, urlStr, dir, filename, maxConn).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CancelPreDownload handles cancellation of pre-download dialog.
 */
export function CancelPreDownload(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(2999425652, taskID);
}

/**
 * CheckFileConflict checks if filename exists in dir and returns conflict status and suggested name.
 */
export function CheckFileConflict(dir: string, filename: string): $CancellablePromise<$models.FileConflictResult> {
    return $Call.ByID(3123179907, dir, filename).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * CheckURLConsistency decides whether a refreshed URL still serves the same file, so existing
 * progress can be reused. headers replaces the task request context when non-nil.
 */
export function CheckURLConsistency(taskID: string, newURL: string, headers: { [_ in string]?: string }): $CancellablePromise<engine$0.ConsistencyResult | null> {
    return $Call.ByID(501855324, taskID, newURL, headers).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ConfirmPreDownload confirms the pre-download task with final user-chosen directory and filename.
 */
export function ConfirmPreDownload(taskID: string, finalDir: string, finalFilename: string, maxConn: number): $CancellablePromise<task$0.Task | null> {
    return $Call.ByID(3194904112, taskID, finalDir, finalFilename, maxConn).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteTask(id: string, deleteDiskFile: boolean): $CancellablePromise<void> {
    return $Call.ByID(2236295855, id, deleteDiskFile);
}

/**
 * GetDefaultDownloadDir returns the default downloads folder
 */
export function GetDefaultDownloadDir(): $CancellablePromise<string> {
    return $Call.ByID(658010303);
}

/**
 * Greet remains for compatibility with existing tests
 */
export function Greet(name: string): $CancellablePromise<string> {
    return $Call.ByID(2659711170, name);
}

/**
 * ListTasks lists all tasks
 */
export function ListTasks(): $CancellablePromise<(task$0.Task | null)[]> {
    return $Call.ByID(3109076673).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * OnTaskUpdated emits wails event to the frontend whenever a task changes
 */
export function OnTaskUpdated(t: task$0.Task | null): $CancellablePromise<void> {
    return $Call.ByID(3922925944, t);
}

/**
 * OpenFile opens the downloaded file with system default application
 */
export function OpenFile(filePath: string): $CancellablePromise<void> {
    return $Call.ByID(1958968983, filePath);
}

/**
 * OpenFolder reveals the downloaded file in the system file manager
 */
export function OpenFolder(folderPath: string): $CancellablePromise<void> {
    return $Call.ByID(3894305329, folderPath);
}

/**
 * PauseTask pauses an active or queued task
 */
export function PauseTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(3621607596, id);
}

/**
 * ProbeURL inspects the URL metadata and reports whether an existing task already uses the URL.
 */
export function ProbeURL(urlStr: string): $CancellablePromise<engine$0.ProbeResult | null> {
    return $Call.ByID(3944315818, urlStr).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ResetAndDownloadWithNewURL discards existing progress and restarts the download from the new URL.
 */
export function ResetAndDownloadWithNewURL(taskID: string, newURL: string, headers: { [_ in string]?: string }): $CancellablePromise<task$0.Task | null> {
    return $Call.ByID(3333862598, taskID, newURL, headers).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ResolveDuplicate resolves a duplicate task using strategies "continue", "redownload", "copy", or "show_completed".
 */
export function ResolveDuplicate(taskID: string, strategy: string, dir: string, filename: string, maxConn: number): $CancellablePromise<task$0.Task | null> {
    return $Call.ByID(2797521964, taskID, strategy, dir, filename, maxConn).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ResumeTask resumes a paused or errored task
 */
export function ResumeTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(1059512591, id);
}

/**
 * RetryTask retries a failed task
 */
export function RetryTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(3354333520, id);
}

/**
 * SelectDirectory opens native directory picker dialog.
 */
export function SelectDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1735672136);
}

/**
 * SetApplication sets the Wails application reference
 */
export function SetApplication(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(4121261467, app);
}

/**
 * StartPreDownload starts downloading in the background while file info dialog is displayed.
 */
export function StartPreDownload(urlStr: string, dir: string, filename: string, maxConn: number): $CancellablePromise<task$0.Task | null> {
    return $Call.ByID(2704757568, urlStr, dir, filename, maxConn).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateTaskURL adopts the refreshed URL and request context, then continues the download.
 */
export function UpdateTaskURL(taskID: string, newURL: string, headers: { [_ in string]?: string }): $CancellablePromise<task$0.Task | null> {
    return $Call.ByID(486323642, taskID, newURL, headers).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = task$0.Task.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.FileConflictResult.createFrom;
const $$createType3 = engine$0.ConsistencyResult.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType1);
const $$createType6 = engine$0.ProbeResult.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
