// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "./internal/engine/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as task$0 from "./internal/task/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as window$0 from "./internal/window/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddTask adds a new download task
 */
export function AddTask(urlStr: string, dir: string, filename: string, maxConn: number): $CancellablePromise<task$0.Task | null> {
    return $Call.ByID(571013529, urlStr, dir, filename, maxConn).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * AssignExtensionToCategory assigns an extension to a target category and updates settings.
 */
export function AssignExtensionToCategory(ext: string, targetCategoryID: string): $CancellablePromise<void> {
    return $Call.ByID(328676256, ext, targetCategoryID);
}

/**
 * CancelCurrentFileInfo cancels the active FileInfo request and advances the queue.
 */
export function CancelCurrentFileInfo(): $CancellablePromise<void> {
    return $Call.ByID(3773381186);
}

/**
 * CancelPreDownload handles cancellation of pre-download dialog.
 */
export function CancelPreDownload(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(2999425652, taskID);
}

/**
 * CheckFileConflict checks if filename exists in dir and returns conflict status and suggested name.
 */
export function CheckFileConflict(dir: string, filename: string): $CancellablePromise<$models.FileConflictResult> {
    return $Call.ByID(3123179907, dir, filename).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * CheckURLConsistency decides whether a refreshed URL still serves the same file, so existing
 * progress can be reused. headers replaces the task request context when non-nil.
 */
export function CheckURLConsistency(taskID: string, newURL: string, headers: { [_ in string]?: string }): $CancellablePromise<engine$0.ConsistencyResult | null> {
    return $Call.ByID(501855324, taskID, newURL, headers).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * CheckURLFilesExist checks if any file previously downloaded with urlStr (or filename variants) exists in dir.
 */
export function CheckURLFilesExist(urlStr: string, dir: string, filename: string): $CancellablePromise<$models.FileConflictResult> {
    return $Call.ByID(3122187214, urlStr, dir, filename).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ConfirmPreDownload confirms the pre-download task with final user-chosen directory and filename.
 */
export function ConfirmPreDownload(taskID: string, finalDir: string, finalFilename: string, maxConn: number): $CancellablePromise<task$0.Task | null> {
    return $Call.ByID(3194904112, taskID, finalDir, finalFilename, maxConn).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteTask(id: string, deleteDiskFile: boolean): $CancellablePromise<void> {
    return $Call.ByID(2236295855, id, deleteDiskFile);
}

/**
 * GetActiveFileInfo returns the active item currently shown in the FileInfo window.
 */
export function GetActiveFileInfo(): $CancellablePromise<window$0.FileInfoItem | null> {
    return $Call.ByID(1899710323).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetDefaultDownloadDir returns the default downloads folder from settings or system fallback
 */
export function GetDefaultDownloadDir(): $CancellablePromise<string> {
    return $Call.ByID(658010303);
}

/**
 * GetFileInfoQueueItems returns all currently enqueued items in the file info window.
 */
export function GetFileInfoQueueItems(): $CancellablePromise<(window$0.FileInfoItem | null)[]> {
    return $Call.ByID(1664868488).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetFileInfoQueueLength returns the number of requests currently waiting in the queue.
 */
export function GetFileInfoQueueLength(): $CancellablePromise<number> {
    return $Call.ByID(2016201816);
}

/**
 * GetSettings returns current active settings
 */
export function GetSettings(): $CancellablePromise<config$0.Settings> {
    return $Call.ByID(2554697378).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetStorageInfo returns current storage mode and directories
 */
export function GetStorageInfo(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(3330596760).then(($result: any) => {
        return $$createType9($result);
    });
}

export function Greet(name: string): $CancellablePromise<string> {
    return $Call.ByID(2659711170, name);
}

/**
 * HideProgressWindow hides the progress window.
 */
export function HideProgressWindow(): $CancellablePromise<void> {
    return $Call.ByID(3377482730);
}

/**
 * ListTasks lists all tasks
 */
export function ListTasks(): $CancellablePromise<(task$0.Task | null)[]> {
    return $Call.ByID(3109076673).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * MinimiseFileInfoWindow minimises the file info window.
 */
export function MinimiseFileInfoWindow(): $CancellablePromise<void> {
    return $Call.ByID(760188354);
}

/**
 * MinimiseProgressWindow minimises the progress window.
 */
export function MinimiseProgressWindow(): $CancellablePromise<void> {
    return $Call.ByID(3189823907);
}

/**
 * OnSettingsUpdated emits wails event to the frontend whenever settings change
 */
export function OnSettingsUpdated(s: config$0.Settings | null): $CancellablePromise<void> {
    return $Call.ByID(3585324432, s);
}

/**
 * OnTaskDeleted emits wails event to the frontend whenever a task is deleted
 */
export function OnTaskDeleted(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(2686073826, taskID);
}

/**
 * OnTaskUpdated emits wails event to the frontend whenever a task changes
 */
export function OnTaskUpdated(t: task$0.Task | null): $CancellablePromise<void> {
    return $Call.ByID(3922925944, t);
}

/**
 * OpenFile opens the downloaded file with system default application after verifying existence
 */
export function OpenFile(filePath: string): $CancellablePromise<void> {
    return $Call.ByID(1958968983, filePath);
}

/**
 * OpenFolder reveals the downloaded file in the system file manager
 */
export function OpenFolder(folderPath: string): $CancellablePromise<void> {
    return $Call.ByID(3894305329, folderPath);
}

/**
 * OpenNewDownload opens the FileInfo window with an empty/manual request.
 */
export function OpenNewDownload(): $CancellablePromise<window$0.DownloadResponse | null> {
    return $Call.ByID(3018225713).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * PauseTask pauses an active or queued task
 */
export function PauseTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(3621607596, id);
}

/**
 * ProbeURL inspects the URL metadata and reports whether an existing task already uses the URL.
 */
export function ProbeURL(urlStr: string): $CancellablePromise<engine$0.ProbeResult | null> {
    return $Call.ByID(3944315818, urlStr).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * ResetAndDownloadWithNewURL discards existing progress and restarts the download from the new URL.
 */
export function ResetAndDownloadWithNewURL(taskID: string, newURL: string, headers: { [_ in string]?: string }): $CancellablePromise<task$0.Task | null> {
    return $Call.ByID(3333862598, taskID, newURL, headers).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ResolveCategoryDirectory resolves the target directory for a given filename based on current settings.
 */
export function ResolveCategoryDirectory(filename: string): $CancellablePromise<string> {
    return $Call.ByID(154355798, filename);
}

/**
 * ResolveDuplicate resolves a duplicate task using strategies "continue", "redownload", "copy", or "show_completed".
 */
export function ResolveDuplicate(taskID: string, strategy: string, dir: string, filename: string, maxConn: number): $CancellablePromise<task$0.Task | null> {
    return $Call.ByID(2797521964, taskID, strategy, dir, filename, maxConn).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ReuseExistingFile moves an existing identical file from another directory to targetDir/targetFilename,
 * cleans stale duplicate tasks, and registers the file as a completed task.
 */
export function ReuseExistingFile(existingTaskID: string, targetDir: string, targetFilename: string): $CancellablePromise<task$0.Task | null> {
    return $Call.ByID(3163272336, existingTaskID, targetDir, targetFilename).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ResumeTask resumes a paused or errored task
 */
export function ResumeTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(1059512591, id);
}

/**
 * RetryProcessingTask retries media processing for a task.
 */
export function RetryProcessingTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(2793104495, id);
}

/**
 * RetryTask retries a failed task
 */
export function RetryTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(3354333520, id);
}

export function SelectDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1735672136);
}

/**
 * SetApplication sets the Wails application reference
 */

/**
 * SetCategoryDirectory sets the save directory for a category by ID and updates settings.
 */
export function SetCategoryDirectory(targetCategoryID: string, directory: string): $CancellablePromise<void> {
    return $Call.ByID(67109910, targetCategoryID, directory);
}
export function SetApplication(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(4121261467, app);
}

/**
 * SetFileInfoWindowHeight dynamically adjusts the fileinfo window's height to wrap its content.
 */
export function SetFileInfoWindowHeight(height: number): $CancellablePromise<void> {
    return $Call.ByID(2015656026, height);
}

/**
 * SetProgressWindowHeight dynamically adjusts the progress window's height between minHeight and maxHeight.
 */
export function SetProgressWindowHeight(height: number): $CancellablePromise<void> {
    return $Call.ByID(2403510243, height);
}

/**
 * ShowMainWindow makes the main window visible and brings it to focus.
 */
export function ShowMainWindow(): $CancellablePromise<void> {
    return $Call.ByID(3189675457);
}

/**
 * ShowProgressWindow brings up or focuses the shared download progress window and highlights the task.
 */
export function ShowProgressWindow(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(593856943, taskID);
}

/**
 * Shutdown is called when the app is terminating to cleanly stop manager and persist state.
 */
export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(2987688963);
}

/**
 * StartPreDownload starts downloading in the background while file info dialog is displayed.
 */
export function StartPreDownload(urlStr: string, dir: string, filename: string, maxConn: number): $CancellablePromise<task$0.Task | null> {
    return $Call.ByID(2704757568, urlStr, dir, filename, maxConn).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SubmitFileInfo confirms the active FileInfo request with user selections.
 */
export function SubmitFileInfo(sub: window$0.FileInfoSubmission): $CancellablePromise<task$0.Task | null> {
    return $Call.ByID(915235023, sub).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SwitchFileInfoActive switches the active file info dialog item to index.
 */
export function SwitchFileInfoActive(index: number): $CancellablePromise<window$0.FileInfoItem | null> {
    return $Call.ByID(2168286885, index).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * TriggerDownload requests a new download, dispatching to FileInfo window queue or duplicate skip policy.
 */
export function TriggerDownload(req: window$0.DownloadRequest): $CancellablePromise<window$0.DownloadResponse | null> {
    return $Call.ByID(2473743423, req).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * UpdateSettings persists updated settings and broadcasts to all windows
 */
export function UpdateSettings(s: config$0.Settings): $CancellablePromise<config$0.Settings> {
    return $Call.ByID(2894041249, s).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * UpdateTaskURL adopts the refreshed URL and request context, then continues the download.
 */
export function UpdateTaskURL(taskID: string, newURL: string, headers: { [_ in string]?: string }): $CancellablePromise<task$0.Task | null> {
    return $Call.ByID(486323642, taskID, newURL, headers).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ValidateDirectory checks whether a directory path exists and is accessible.
 */
export function ValidateDirectory(dirPath: string): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(2018273234, dirPath);
}

// Private type creation functions
const $$createType0 = task$0.Task.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.FileConflictResult.createFrom;
const $$createType3 = engine$0.ConsistencyResult.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = window$0.FileInfoItem.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = config$0.Settings.createFrom;
const $$createType9 = $Create.Map($Create.Any, $Create.Any);
const $$createType10 = $Create.Array($$createType1);
const $$createType11 = window$0.DownloadResponse.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = engine$0.ProbeResult.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
