// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as duplicate$0 from "./internal/duplicate/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "./internal/engine/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as server$0 from "./internal/server/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as task$0 from "./internal/task/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as window$0 from "./internal/window/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddTask adds a new download task
 */
export function AddTask(urlStr: string, dir: string, filename: string, maxConn: number): $CancellablePromise<task$0.Task | null> {
    return $Call.ByID(571013529, urlStr, dir, filename, maxConn).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * AssignExtensionToCategory assigns an extension to a target category and updates settings.
 */
export function AssignExtensionToCategory(ext: string, targetCategoryID: string): $CancellablePromise<void> {
    return $Call.ByID(328676256, ext, targetCategoryID);
}

/**
 * CancelCurrentFileInfo cancels the active FileInfo request and advances the queue.
 */
export function CancelCurrentFileInfo(): $CancellablePromise<void> {
    return $Call.ByID(3773381186);
}

/**
 * CancelPreDownload handles cancellation of pre-download dialog.
 */
export function CancelPreDownload(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(2999425652, taskID);
}

/**
 * CheckFileConflict checks if filename exists in dir and returns conflict status and suggested name.
 */
export function CheckFileConflict(dir: string, filename: string): $CancellablePromise<$models.FileConflictResult> {
    return $Call.ByID(3123179907, dir, filename).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * CheckURLConsistency decides whether a refreshed URL still serves the same file, so existing
 * progress can be reused. headers replaces the task request context when non-nil.
 */
export function CheckURLConsistency(taskID: string, newURL: string, headers: { [_ in string]?: string }): $CancellablePromise<engine$0.ConsistencyResult | null> {
    return $Call.ByID(501855324, taskID, newURL, headers).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * CheckURLFilesExist checks if any file previously downloaded with urlStr (or filename variants) exists in dir.
 */
export function CheckURLFilesExist(urlStr: string, dir: string, filename: string): $CancellablePromise<$models.FileConflictResult> {
    return $Call.ByID(3122187214, urlStr, dir, filename).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ConfirmPreDownload confirms the pre-download task with final user-chosen directory and filename.
 */
export function ConfirmPreDownload(taskID: string, finalDir: string, finalFilename: string, maxConn: number): $CancellablePromise<task$0.Task | null> {
    return $Call.ByID(3194904112, taskID, finalDir, finalFilename, maxConn).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteTask(id: string, deleteDiskFile: boolean): $CancellablePromise<void> {
    return $Call.ByID(2236295855, id, deleteDiskFile);
}

/**
 * GetActiveFileInfo returns the active item currently shown in the FileInfo window.
 */
export function GetActiveFileInfo(): $CancellablePromise<window$0.FileInfoItem | null> {
    return $Call.ByID(1899710323).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetDefaultDownloadDir returns the default downloads folder from settings or system fallback
 */
export function GetDefaultDownloadDir(): $CancellablePromise<string> {
    return $Call.ByID(658010303);
}

/**
 * GetFileInfoQueueItems returns all currently enqueued items in the file info window.
 */
export function GetFileInfoQueueItems(): $CancellablePromise<(window$0.FileInfoItem | null)[]> {
    return $Call.ByID(1664868488).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetFileInfoQueueLength returns the number of requests currently waiting in the queue.
 */
export function GetFileInfoQueueLength(): $CancellablePromise<number> {
    return $Call.ByID(2016201816);
}

/**
 * GetServerStatus returns the active loopback server runtime status.
 */
export function GetServerStatus(): $CancellablePromise<server$0.Status> {
    return $Call.ByID(880383150).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetSettings returns current active settings
 */
export function GetSettings(): $CancellablePromise<config$0.Settings> {
    return $Call.ByID(2554697378).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetStorageInfo returns current storage mode and directories
 */
export function GetStorageInfo(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(3330596760).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * HideProgressWindow hides the progress window.
 */
export function HideProgressWindow(): $CancellablePromise<void> {
    return $Call.ByID(3377482730);
}

/**
 * IsLaunchAtStartup reports whether autostart is enabled in system/settings.
 */
export function IsLaunchAtStartup(): $CancellablePromise<boolean> {
    return $Call.ByID(1534902556);
}

/**
 * IsProgressWindowAlwaysOnTop reports whether the progress window is set to always on top.
 */
export function IsProgressWindowAlwaysOnTop(): $CancellablePromise<boolean> {
    return $Call.ByID(351100157);
}

/**
 * ListTasks lists all tasks
 */
export function ListTasks(): $CancellablePromise<(task$0.Task | null)[]> {
    return $Call.ByID(3109076673).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * MinimiseFileInfoWindow minimises the file info window.
 */
export function MinimiseFileInfoWindow(): $CancellablePromise<void> {
    return $Call.ByID(760188354);
}

/**
 * MinimiseProgressWindow minimises the progress window.
 */
export function MinimiseProgressWindow(): $CancellablePromise<void> {
    return $Call.ByID(3189823907);
}

/**
 * OnSettingsUpdated applies changed settings to the running engine and broadcasts them.
 * 应用代理可能失败，错误交回发起更新的调用方，避免界面继续显示一个实际未生效的代理。
 */
export function OnSettingsUpdated(s: config$0.Settings | null): $CancellablePromise<void> {
    return $Call.ByID(3585324432, s);
}

/**
 * OnTaskDeleted emits wails event to the frontend whenever a task is deleted
 */
export function OnTaskDeleted(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(2686073826, taskID);
}

/**
 * OnTaskUpdated emits wails event to the frontend whenever a task changes
 */
export function OnTaskUpdated(t: task$0.Task | null): $CancellablePromise<void> {
    return $Call.ByID(3922925944, t);
}

/**
 * OpenFile opens the downloaded file with system default application after verifying existence
 */
export function OpenFile(filePath: string): $CancellablePromise<void> {
    return $Call.ByID(1958968983, filePath);
}

/**
 * OpenFolder reveals the downloaded file in the system file manager
 */
export function OpenFolder(folderPath: string): $CancellablePromise<void> {
    return $Call.ByID(3894305329, folderPath);
}

/**
 * OpenNewDownload opens the FileInfo window with an empty/manual request.
 */
export function OpenNewDownload(): $CancellablePromise<window$0.DownloadResponse | null> {
    return $Call.ByID(3018225713).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * PauseTask pauses an active or queued task
 */
export function PauseTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(3621607596, id);
}

/**
 * ProbeMediaDuration 读远端音视频文件的时长（秒），供文件信息窗口在下载前展示。
 * 识别不出来返回 0：时长是附加信息，不是下载流程的一环，读不到就不显示，绝不编一个数值。
 */
export function ProbeMediaDuration(urlStr: string, filename: string, totalBytes: number): $CancellablePromise<number> {
    return $Call.ByID(564875139, urlStr, filename, totalBytes);
}

/**
 * ProbeURL inspects the URL metadata and reports whether an existing task already uses the URL.
 * 手动改链接时由文件信息窗口调用，因此带上这一项的请求上下文，与登记时的探测口径一致。
 */
export function ProbeURL(urlStr: string): $CancellablePromise<engine$0.ProbeResult | null> {
    return $Call.ByID(3944315818, urlStr).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * ResetAndDownloadWithNewURL discards existing progress and restarts the download from the new URL.
 */
export function ResetAndDownloadWithNewURL(taskID: string, newURL: string, headers: { [_ in string]?: string }): $CancellablePromise<task$0.Task | null> {
    return $Call.ByID(3333862598, taskID, newURL, headers).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ResolveDestination resolves the save directory and matched category for a filename.
 * 分类规则只在后端实现一次：界面用它展示命中分类并填充目录，不再自建同一规则。
 */
export function ResolveDestination(filename: string): $CancellablePromise<$models.DestinationInfo> {
    return $Call.ByID(177293617, filename).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * ResolveDuplicate resolves a duplicate task using strategies "continue", "redownload", "copy", or "show_completed".
 */
export function ResolveDuplicate(taskID: string, strategy: string, dir: string, filename: string, maxConn: number): $CancellablePromise<task$0.Task | null> {
    return $Call.ByID(2797521964, taskID, strategy, dir, filename, maxConn).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ResolveDuplicateDecision 按给定链接与最终保存位置裁决这次重复该给哪些动作、默认执行哪个。
 * 界面在链接、文件名或目录变化后调用它刷新选项；裁决规则只在 duplicate 包实现一次，
 * 界面不据策略自行推导（ADR-0002：后端为唯一事实来源）。
 */
export function ResolveDuplicateDecision(urlStr: string, dir: string, filename: string): $CancellablePromise<duplicate$0.Decision> {
    return $Call.ByID(687526930, urlStr, dir, filename).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * RestartServer restarts the local HTTP loopback server on the specified port.
 * If port <= 0, it uses the port configured in settings.
 */
export function RestartServer(port: number): $CancellablePromise<number> {
    return $Call.ByID(3691977863, port);
}

/**
 * ResumeTask resumes a paused or errored task
 */
export function ResumeTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(1059512591, id);
}

/**
 * RetryProcessingTask retries media processing for a task.
 */
export function RetryProcessingTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(2793104495, id);
}

/**
 * RetryTask retries a failed task
 */
export function RetryTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(3354333520, id);
}

/**
 * ReuseExistingFile moves an existing identical file from another directory to targetDir/targetFilename,
 * cleans stale duplicate tasks, and registers the file as a completed task.
 */
export function ReuseExistingFile(existingTaskID: string, targetDir: string, targetFilename: string): $CancellablePromise<task$0.Task | null> {
    return $Call.ByID(3163272336, existingTaskID, targetDir, targetFilename).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SelectDirectory(defaultDir: string): $CancellablePromise<string> {
    return $Call.ByID(1735672136, defaultDir);
}

/**
 * SelectHLSVariant 记下用户在文件信息窗口里选定的清晰度，并把这一版的事实（大小、时长）
 * 取回来。多清晰度的清单必须先选定才能提交；只有一项时不构成选择，无需调用。
 * urlStr 由界面把当前链接显式传进来：手输链接时队列项里没有登记过 URL。
 */
export function SelectHLSVariant(requestID: string, urlStr: string, variantURI: string): $CancellablePromise<void> {
    return $Call.ByID(2368695079, requestID, urlStr, variantURI);
}

/**
 * SetCategoryDirectory sets the save directory for a category by ID and updates settings.
 */
export function SetCategoryDirectory(targetCategoryID: string, directory: string): $CancellablePromise<void> {
    return $Call.ByID(67109910, targetCategoryID, directory);
}

/**
 * SetFileInfoWindowHeight dynamically adjusts the fileinfo window's height to wrap its content.
 */
export function SetFileInfoWindowHeight(height: number): $CancellablePromise<void> {
    return $Call.ByID(2015656026, height);
}

/**
 * SetLaunchAtStartup configures whether SheepGet starts at system login.
 */
export function SetLaunchAtStartup(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(749774982, enabled);
}

/**
 * SetProgressWindowHeight adjusts the progress window's height to wrap its content.
 * 高度由内容决定：只有一个任务卡片时窗口就收成一张卡片的高度，不套用内容意义上的下限，
 * 只有超过上限时才封顶（超出部分由窗口内部滚动）。
 */
export function SetProgressWindowHeight(height: number): $CancellablePromise<void> {
    return $Call.ByID(2403510243, height);
}

/**
 * ShowMainWindow makes the main window visible and brings it to focus.
 */
export function ShowMainWindow(): $CancellablePromise<void> {
    return $Call.ByID(3189675457);
}

/**
 * ShowProgressWindow brings up or focuses the shared download progress window and highlights the task.
 */
export function ShowProgressWindow(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(593856943, taskID);
}

/**
 * Shutdown is called when the app is terminating to cleanly stop manager and persist state.
 */
export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(2987688963);
}

/**
 * StartPreDownload starts downloading in the background while file info dialog is displayed.
 */
export function StartPreDownload(urlStr: string, dir: string, filename: string, maxConn: number): $CancellablePromise<task$0.Task | null> {
    return $Call.ByID(2704757568, urlStr, dir, filename, maxConn).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SubmitFileInfo confirms the active FileInfo request with user selections.
 */
export function SubmitFileInfo(sub: window$0.FileInfoSubmission): $CancellablePromise<task$0.Task | null> {
    return $Call.ByID(915235023, sub).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SwitchFileInfoActive switches the active file info dialog item to index.
 */
export function SwitchFileInfoActive(index: number): $CancellablePromise<window$0.FileInfoItem | null> {
    return $Call.ByID(2168286885, index).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * ToggleProgressWindowAlwaysOnTop toggles whether the progress window is always on top.
 */
export function ToggleProgressWindowAlwaysOnTop(): $CancellablePromise<boolean> {
    return $Call.ByID(692290461);
}

/**
 * TriggerDownload requests a new download, dispatching to FileInfo window queue or duplicate skip policy.
 */
export function TriggerDownload(req: window$0.DownloadRequest): $CancellablePromise<window$0.DownloadResponse | null> {
    return $Call.ByID(2473743423, req).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * UpdateSettings persists updated settings and broadcasts to all windows
 */
export function UpdateSettings(s: config$0.Settings): $CancellablePromise<config$0.Settings> {
    return $Call.ByID(2894041249, s).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * UpdateTaskURL adopts the refreshed URL and request context, then continues the download.
 */
export function UpdateTaskURL(taskID: string, newURL: string, headers: { [_ in string]?: string }): $CancellablePromise<task$0.Task | null> {
    return $Call.ByID(486323642, taskID, newURL, headers).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ValidateDirectory checks whether a directory path exists and is accessible.
 */
export function ValidateDirectory(dirPath: string): $CancellablePromise<[boolean, string]> {
    return $Call.ByID(2018273234, dirPath);
}

// Private type creation functions
const $$createType0 = task$0.Task.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.FileConflictResult.createFrom;
const $$createType3 = engine$0.ConsistencyResult.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = window$0.FileInfoItem.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = server$0.Status.createFrom;
const $$createType9 = config$0.Settings.createFrom;
const $$createType10 = $Create.Map($Create.Any, $Create.Any);
const $$createType11 = $Create.Array($$createType1);
const $$createType12 = window$0.DownloadResponse.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = engine$0.ProbeResult.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = $models.DestinationInfo.createFrom;
const $$createType17 = duplicate$0.Decision.createFrom;
