// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DestinationInfo describes the resolved save location of a download: its directory and
 * the category that matched the filename.
 */
export class DestinationInfo {
    "directory": string;
    "categoryId": string;

    /** Creates a new DestinationInfo instance. */
    constructor($$source: Partial<DestinationInfo> = {}) {
        if (!("directory" in $$source)) {
            this["directory"] = "";
        }
        if (!("categoryId" in $$source)) {
            this["categoryId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DestinationInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DestinationInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DestinationInfo($$parsedSource as Partial<DestinationInfo>);
    }
}

/**
 * FileConflictResult represents whether target file exists and suggests an alternative filename.
 */
export class FileConflictResult {
    "exists": boolean;
    "suggestedFilename": string;
    "existingPath"?: string;
    "existingTaskID"?: string;
    "canReuseExistingFile"?: boolean;

    /** Creates a new FileConflictResult instance. */
    constructor($$source: Partial<FileConflictResult> = {}) {
        if (!("exists" in $$source)) {
            this["exists"] = false;
        }
        if (!("suggestedFilename" in $$source)) {
            this["suggestedFilename"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileConflictResult instance from a string or object.
     */
    static createFrom($$source: any = {}): FileConflictResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileConflictResult($$parsedSource as Partial<FileConflictResult>);
    }
}
