// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Action 是一次裁决给出的可执行动作。取值与 engine.ResolveDuplicate 的执行分支一一对应，
 * 因此后端收到界面回传的动作后可以直接执行，不需要再次翻译。
 */
export enum Action {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * ActionContinue 续传历史任务，保留已下载的分片。
     */
    ActionContinue = "continue",

    /**
     * ActionRedownload 丢弃历史任务与残留分片，重新创建任务下载。
     */
    ActionRedownload = "redownload",

    /**
     * ActionCopy 以序号副本另存，历史任务保持不动。
     */
    ActionCopy = "copy",

    /**
     * ActionShowCompleted 不下载，只查看历史任务的完成记录。
     */
    ActionShowCompleted = "show_completed",

    /**
     * ActionReuse 复用其他目录里已有的成品文件，不重新下载。
     * 
     * 它不由重复链接策略推导，而是来自「其他目录已存在同一份成品」这一独立事实，
     * 由界面在存在可复用文件时提供额外入口；这里保留取值以便提交契约完整。
     */
    ActionReuse = "reuse",
};

/**
 * Case 是目标位置与历史任务共同构成的客观局面。界面按它决定显示哪种提示。
 */
export enum Case {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * CaseNone 没有同一 URL 的历史任务，无需裁决；同名文件冲突另行独立处理。
     */
    CaseNone = "",

    /**
     * CaseDestinationOccupied 目标位置已有成品文件：三个动作都有意义，用户需要选择。
     */
    CaseDestinationOccupied = "destination_occupied",

    /**
     * CaseHistoryFileAbsent 历史任务已完成，但成品文件已不在目标位置（被删除或移走）：
     * 没有可续传的进度，也没有可覆盖的文件，只剩重新下载。
     */
    CaseHistoryFileAbsent = "history_file_absent",

    /**
     * CaseHistoryUnfinished 历史任务尚未完成：分片就是全部价值所在，续传是唯一有意义的动作。
     */
    CaseHistoryUnfinished = "history_unfinished",
};

/**
 * Decision 是裁决结果。
 */
export class Decision {
    "case": Case;

    /**
     * Options 是界面应当呈现的选项，顺序即展示顺序。为空表示动作已定、无需用户选择。
     */
    "options"?: Action[];

    /**
     * Default 是用户没有另行选择时执行的动作，同时也是界面默认选中项。
     * 为空表示必须先由用户选定一项，否则不能开始下载。
     */
    "default"?: Action;

    /**
     * ShowCompleted 表示登记这次重复时应当唤起共享下载进度窗口的完成区域。
     * 由「跳过并显示完成」策略加上「历史任务已完成」这个事实共同决定。
     */
    "showCompleted"?: boolean;

    /** Creates a new Decision instance. */
    constructor($$source: Partial<Decision> = {}) {
        if (!("case" in $$source)) {
            this["case"] = Case.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Decision instance from a string or object.
     */
    static createFrom($$source: any = {}): Decision {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField1_0($$parsedSource["options"]);
        }
        return new Decision($$parsedSource as Partial<Decision>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
