version: '3'

vars:
  APP_NAME: 'SheepGet'
  BIN_DIR: 'build/bin'

tasks:
  build:
    desc: Builds the application
    cmds:
      - '{{if eq .DEV "true"}}go build{{if .EXTRA_TAGS}} -tags {{.EXTRA_TAGS}}{{end}} -o {{.BIN_DIR}}/{{.APP_NAME}}{{exeExt}} .{{else}}go build -tags production{{if .EXTRA_TAGS}},{{.EXTRA_TAGS}}{{end}} -trimpath -ldflags="-w -s{{if eq OS "windows"}} -H=windowsgui{{end}}" -o {{.BIN_DIR}}/{{.APP_NAME}}{{exeExt}} .{{end}}'

  run:
    desc: Runs the application binary
    cmds:
      - '{{.BIN_DIR}}/{{.APP_NAME}}{{exeExt}}'

  dev:frontend:
    desc: Runs the frontend dev server
    dir: frontend
    cmds:
      - bun run dev --port {{.WAILS_VITE_PORT | default 9245}}

  package:
    desc: Packages the application for distribution
    cmds:
      - node scripts/package.mjs
