// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Status represents the runtime status of the loopback HTTP and WebSocket server.
 */
export class Status {
    "running": boolean;
    "port": number;
    "connectedCount": number;
    "error"?: string;

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("connectedCount" in $$source)) {
            this["connectedCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Status($$parsedSource as Partial<Status>);
    }
}
