// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppearanceConfig specifies UI appearance settings.
 */
export class AppearanceConfig {
    "theme": ThemeMode;
    "accentColor": string;

    /** Creates a new AppearanceConfig instance. */
    constructor($$source: Partial<AppearanceConfig> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = ThemeMode.$zero;
        }
        if (!("accentColor" in $$source)) {
            this["accentColor"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppearanceConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AppearanceConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppearanceConfig($$parsedSource as Partial<AppearanceConfig>);
    }
}

/**
 * DownloadConfig specifies download engine and directory rules.
 */
export class DownloadConfig {
    "duplicateUrlPolicy": DuplicateURLPolicy;
    "preDownload": boolean;
    "maxConcurrentDownloads": number;
    "defaultConnectionsPerTask": number;
    "defaultDirectory": string;
    "tempDirectory": string;

    /** Creates a new DownloadConfig instance. */
    constructor($$source: Partial<DownloadConfig> = {}) {
        if (!("duplicateUrlPolicy" in $$source)) {
            this["duplicateUrlPolicy"] = DuplicateURLPolicy.$zero;
        }
        if (!("preDownload" in $$source)) {
            this["preDownload"] = false;
        }
        if (!("maxConcurrentDownloads" in $$source)) {
            this["maxConcurrentDownloads"] = 0;
        }
        if (!("defaultConnectionsPerTask" in $$source)) {
            this["defaultConnectionsPerTask"] = 0;
        }
        if (!("defaultDirectory" in $$source)) {
            this["defaultDirectory"] = "";
        }
        if (!("tempDirectory" in $$source)) {
            this["tempDirectory"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): DownloadConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadConfig($$parsedSource as Partial<DownloadConfig>);
    }
}

/**
 * DuplicateURLPolicy specifies how duplicate URLs should be handled.
 */
export enum DuplicateURLPolicy {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DuplicatePolicyPrompt = "prompt",
    DuplicatePolicySkipShowCompleted = "skip_show_completed",
    DuplicatePolicyContinueOverwrite = "continue_overwrite",
    DuplicatePolicyNumberedCopy = "numbered_copy",

    /**
     * Aliases maintained for backwards compatibility
     */
    DuplicatePolicyAsk = "prompt",
    DuplicatePolicySkipShowDone = "skip_show_completed",
    DuplicatePolicyOverwrite = "continue_overwrite",
    DuplicatePolicySkipShowLegacy = "skip_show_done",
    DuplicatePolicyOverwriteLegacy = "overwrite",
};

/**
 * Settings represents the root settings structure.
 */
export class Settings {
    "appearance": AppearanceConfig;
    "download": DownloadConfig;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("appearance" in $$source)) {
            this["appearance"] = (new AppearanceConfig());
        }
        if (!("download" in $$source)) {
            this["download"] = (new DownloadConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("appearance" in $$parsedSource) {
            $$parsedSource["appearance"] = $$createField0_0($$parsedSource["appearance"]);
        }
        if ("download" in $$parsedSource) {
            $$parsedSource["download"] = $$createField1_0($$parsedSource["download"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

/**
 * ThemeMode specifies the UI theme mode.
 */
export enum ThemeMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ThemeSystem = "system",
    ThemeLight = "light",
    ThemeDark = "dark",
};

// Private type creation functions
const $$createType0 = AppearanceConfig.createFrom;
const $$createType1 = DownloadConfig.createFrom;
