// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppearanceConfig specifies UI appearance settings.
 */
export class AppearanceConfig {
    "theme": ThemeMode;
    "accentColor": string;

    /** Creates a new AppearanceConfig instance. */
    constructor($$source: Partial<AppearanceConfig> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = ThemeMode.$zero;
        }
        if (!("accentColor" in $$source)) {
            this["accentColor"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppearanceConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AppearanceConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppearanceConfig($$parsedSource as Partial<AppearanceConfig>);
    }
}

/**
 * CategoryConfig specifies an automatic archiving category rule.
 */
export class CategoryConfig {
    "id": string;
    "name": string;
    "directory": string;
    "extensions": string[];
    "isBuiltin": boolean;

    /** Creates a new CategoryConfig instance. */
    constructor($$source: Partial<CategoryConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("directory" in $$source)) {
            this["directory"] = "";
        }
        if (!("extensions" in $$source)) {
            this["extensions"] = [];
        }
        if (!("isBuiltin" in $$source)) {
            this["isBuiltin"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CategoryConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): CategoryConfig {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField3_0($$parsedSource["extensions"]);
        }
        return new CategoryConfig($$parsedSource as Partial<CategoryConfig>);
    }
}

/**
 * ClipboardConfig specifies clipboard monitoring settings.
 */
export class ClipboardConfig {
    "enabled": boolean;

    /** Creates a new ClipboardConfig instance. */
    constructor($$source: Partial<ClipboardConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClipboardConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ClipboardConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClipboardConfig($$parsedSource as Partial<ClipboardConfig>);
    }
}

/**
 * DownloadConfig specifies download engine and directory rules.
 */
export class DownloadConfig {
    "duplicateUrlPolicy": DuplicateURLPolicy;
    "preDownload": boolean;
    "maxConcurrentDownloads": number;
    "defaultConnectionsPerTask": number;
    "defaultDirectory": string;
    "tempDirectory": string;
    "useServerFileTime": boolean;
    "showProgressWindow": boolean;
    "keepCompletedInfo": boolean;
    "autoRemoveCompletedOnOpen": boolean;
    "builtinCategories": CategoryConfig[];
    "customCategories": CategoryConfig[];

    /** Creates a new DownloadConfig instance. */
    constructor($$source: Partial<DownloadConfig> = {}) {
        if (!("duplicateUrlPolicy" in $$source)) {
            this["duplicateUrlPolicy"] = DuplicateURLPolicy.$zero;
        }
        if (!("preDownload" in $$source)) {
            this["preDownload"] = false;
        }
        if (!("maxConcurrentDownloads" in $$source)) {
            this["maxConcurrentDownloads"] = 0;
        }
        if (!("defaultConnectionsPerTask" in $$source)) {
            this["defaultConnectionsPerTask"] = 0;
        }
        if (!("defaultDirectory" in $$source)) {
            this["defaultDirectory"] = "";
        }
        if (!("tempDirectory" in $$source)) {
            this["tempDirectory"] = "";
        }
        if (!("useServerFileTime" in $$source)) {
            this["useServerFileTime"] = false;
        }
        if (!("showProgressWindow" in $$source)) {
            this["showProgressWindow"] = false;
        }
        if (!("keepCompletedInfo" in $$source)) {
            this["keepCompletedInfo"] = false;
        }
        if (!("autoRemoveCompletedOnOpen" in $$source)) {
            this["autoRemoveCompletedOnOpen"] = false;
        }
        if (!("builtinCategories" in $$source)) {
            this["builtinCategories"] = [];
        }
        if (!("customCategories" in $$source)) {
            this["customCategories"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): DownloadConfig {
        const $$createField10_0 = $$createType2;
        const $$createField11_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("builtinCategories" in $$parsedSource) {
            $$parsedSource["builtinCategories"] = $$createField10_0($$parsedSource["builtinCategories"]);
        }
        if ("customCategories" in $$parsedSource) {
            $$parsedSource["customCategories"] = $$createField11_0($$parsedSource["customCategories"]);
        }
        return new DownloadConfig($$parsedSource as Partial<DownloadConfig>);
    }
}

/**
 * DuplicateURLPolicy specifies how duplicate URLs should be handled.
 */
export enum DuplicateURLPolicy {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DuplicatePolicyPrompt = "prompt",
    DuplicatePolicySkipShowCompleted = "skip_show_completed",
    DuplicatePolicyContinueOverwrite = "continue_overwrite",
    DuplicatePolicyNumberedCopy = "numbered_copy",

    /**
     * Aliases maintained for backwards compatibility
     */
    DuplicatePolicyAsk = "prompt",
    DuplicatePolicySkipShowDone = "skip_show_completed",
    DuplicatePolicyOverwrite = "continue_overwrite",
    DuplicatePolicySkipShowLegacy = "skip_show_done",
    DuplicatePolicyOverwriteLegacy = "overwrite",
};

/**
 * GeneralConfig specifies general application settings like autostart and server port.
 */
export class GeneralConfig {
    "launchAtStartup": boolean;
    "silentStartup": boolean;
    "lightweightMode": boolean;

    /**
     * EnableLogging 控制是否把运行日志写进数据目录的 logs/。默认关闭：正常使用不落盘，
     * 需要排查时才打开（滚动上限见 internal/logging）。
     */
    "enableLogging": boolean;
    "serverPort": number;

    /** Creates a new GeneralConfig instance. */
    constructor($$source: Partial<GeneralConfig> = {}) {
        if (!("launchAtStartup" in $$source)) {
            this["launchAtStartup"] = false;
        }
        if (!("silentStartup" in $$source)) {
            this["silentStartup"] = false;
        }
        if (!("lightweightMode" in $$source)) {
            this["lightweightMode"] = false;
        }
        if (!("enableLogging" in $$source)) {
            this["enableLogging"] = false;
        }
        if (!("serverPort" in $$source)) {
            this["serverPort"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GeneralConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): GeneralConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GeneralConfig($$parsedSource as Partial<GeneralConfig>);
    }
}

/**
 * ProxyConfig specifies application network proxy settings.
 */
export class ProxyConfig {
    "mode": ProxyMode;
    "customAddr": string;

    /** Creates a new ProxyConfig instance. */
    constructor($$source: Partial<ProxyConfig> = {}) {
        if (!("mode" in $$source)) {
            this["mode"] = ProxyMode.$zero;
        }
        if (!("customAddr" in $$source)) {
            this["customAddr"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ProxyConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProxyConfig($$parsedSource as Partial<ProxyConfig>);
    }
}

/**
 * ProxyMode specifies the proxy strategy.
 */
export enum ProxyMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ProxyModeDirect = "direct",
    ProxyModeSystem = "system",
    ProxyModeCustom = "custom",
};

/**
 * Settings represents the root settings structure.
 */
export class Settings {
    "general": GeneralConfig;
    "appearance": AppearanceConfig;
    "download": DownloadConfig;
    "proxy": ProxyConfig;
    "takeover": TakeoverConfig;
    "clipboard": ClipboardConfig;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("general" in $$source)) {
            this["general"] = (new GeneralConfig());
        }
        if (!("appearance" in $$source)) {
            this["appearance"] = (new AppearanceConfig());
        }
        if (!("download" in $$source)) {
            this["download"] = (new DownloadConfig());
        }
        if (!("proxy" in $$source)) {
            this["proxy"] = (new ProxyConfig());
        }
        if (!("takeover" in $$source)) {
            this["takeover"] = (new TakeoverConfig());
        }
        if (!("clipboard" in $$source)) {
            this["clipboard"] = (new ClipboardConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType5;
        const $$createField3_0 = $$createType6;
        const $$createField4_0 = $$createType7;
        const $$createField5_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("general" in $$parsedSource) {
            $$parsedSource["general"] = $$createField0_0($$parsedSource["general"]);
        }
        if ("appearance" in $$parsedSource) {
            $$parsedSource["appearance"] = $$createField1_0($$parsedSource["appearance"]);
        }
        if ("download" in $$parsedSource) {
            $$parsedSource["download"] = $$createField2_0($$parsedSource["download"]);
        }
        if ("proxy" in $$parsedSource) {
            $$parsedSource["proxy"] = $$createField3_0($$parsedSource["proxy"]);
        }
        if ("takeover" in $$parsedSource) {
            $$parsedSource["takeover"] = $$createField4_0($$parsedSource["takeover"]);
        }
        if ("clipboard" in $$parsedSource) {
            $$parsedSource["clipboard"] = $$createField5_0($$parsedSource["clipboard"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

/**
 * TakeoverConfig specifies automatic browser takeover rules such as excluded sites and shortcuts.
 */
export class TakeoverConfig {
    "excludedSites": string[];
    "pauseShortcut": string;
    "forceShortcut": string;

    /** Creates a new TakeoverConfig instance. */
    constructor($$source: Partial<TakeoverConfig> = {}) {
        if (!("excludedSites" in $$source)) {
            this["excludedSites"] = [];
        }
        if (!("pauseShortcut" in $$source)) {
            this["pauseShortcut"] = "";
        }
        if (!("forceShortcut" in $$source)) {
            this["forceShortcut"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TakeoverConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): TakeoverConfig {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("excludedSites" in $$parsedSource) {
            $$parsedSource["excludedSites"] = $$createField0_0($$parsedSource["excludedSites"]);
        }
        return new TakeoverConfig($$parsedSource as Partial<TakeoverConfig>);
    }
}

/**
 * ThemeMode specifies the UI theme mode.
 */
export enum ThemeMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ThemeSystem = "system",
    ThemeLight = "light",
    ThemeDark = "dark",
};

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = CategoryConfig.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = GeneralConfig.createFrom;
const $$createType4 = AppearanceConfig.createFrom;
const $$createType5 = DownloadConfig.createFrom;
const $$createType6 = ProxyConfig.createFrom;
const $$createType7 = TakeoverConfig.createFrom;
const $$createType8 = ClipboardConfig.createFrom;
