// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Inputs 是一次传输已经落盘的输入：初始化片段与按播放顺序排列的媒体分片。
 * 
 * 存的是分片目录内的文件名而不是绝对路径：这份输入要随任务一起持久化，重启、换临时目录、
 * 换机器之后仍然对得上（见 Paths）。
 */
export class Inputs {
    "init"?: string[];
    "segments": string[];

    /** Creates a new Inputs instance. */
    constructor($$source: Partial<Inputs> = {}) {
        if (!("segments" in $$source)) {
            this["segments"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Inputs instance from a string or object.
     */
    static createFrom($$source: any = {}): Inputs {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("init" in $$parsedSource) {
            $$parsedSource["init"] = $$createField0_0($$parsedSource["init"]);
        }
        if ("segments" in $$parsedSource) {
            $$parsedSource["segments"] = $$createField1_0($$parsedSource["segments"]);
        }
        return new Inputs($$parsedSource as Partial<Inputs>);
    }
}

/**
 * Source 是一次 HLS 下载选定后的事实。它既足以重新取回清单（后端的续传与重试都靠它），
 * 也足以在界面上说明这次下载（清晰度、时长、分片数）。
 */
export class Source {
    "playlistUrl": string;
    "variant": Variant;

    /**
     * AudioURI 是独立音轨的媒体清单地址；音视频分离的清单必须一并下载才能拼出完整成品。
     */
    "audioUri"?: string;

    /**
     * Duration 是清单声明的总时长（秒）。它是可获得的已知信息，界面据此展示。
     */
    "duration"?: number;
    "segments"?: number;

    /**
     * TotalBytes 是这次下载的总大小；-1 表示还没确定，界面按未知显示。
     * 分片长度通常不在清单里（除非用了 BYTERANGE），因此它多半要靠逐分片询问才能得到。
     */
    "totalBytes"?: number;

    /** Creates a new Source instance. */
    constructor($$source: Partial<Source> = {}) {
        if (!("playlistUrl" in $$source)) {
            this["playlistUrl"] = "";
        }
        if (!("variant" in $$source)) {
            this["variant"] = (new Variant());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Source instance from a string or object.
     */
    static createFrom($$source: any = {}): Source {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("variant" in $$parsedSource) {
            $$parsedSource["variant"] = $$createField1_0($$parsedSource["variant"]);
        }
        return new Source($$parsedSource as Partial<Source>);
    }
}

/**
 * Variant 是主清单里的一个清晰度选项，对应一条 EXT-X-STREAM-INF 及其后的媒体清单地址。
 */
export class Variant {
    "uri": string;
    "bandwidth": number;
    "width"?: number;
    "height"?: number;
    "codecs"?: string;
    "name"?: string;
    "frameRate"?: number;
    "audioGroupId"?: string;

    /** Creates a new Variant instance. */
    constructor($$source: Partial<Variant> = {}) {
        if (!("uri" in $$source)) {
            this["uri"] = "";
        }
        if (!("bandwidth" in $$source)) {
            this["bandwidth"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Variant instance from a string or object.
     */
    static createFrom($$source: any = {}): Variant {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Variant($$parsedSource as Partial<Variant>);
    }
}

/**
 * VariantOption 是给界面看的清晰度选项：只有用户据以做决定、以及回传给后端的那几项。
 * 清单地址与码率来自 EXT-X-STREAM-INF；展示名（Label）已把分辨率说清楚（如 1080P），
 * 界面据此渲染即可，不需要再读一遍宽高。
 */
export class VariantOption {
    "uri": string;
    "label": string;
    "bandwidth"?: number;

    /** Creates a new VariantOption instance. */
    constructor($$source: Partial<VariantOption> = {}) {
        if (!("uri" in $$source)) {
            this["uri"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VariantOption instance from a string or object.
     */
    static createFrom($$source: any = {}): VariantOption {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VariantOption($$parsedSource as Partial<VariantOption>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Variant.createFrom;
