// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as credentials$0 from "../credentials/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as hls$0 from "../hls/models.js";

/**
 * Chunk represents a segment of a file being downloaded.
 */
export class Chunk {
    "index": number;
    "start": number;
    "end": number;
    "downloaded": number;
    "assisted": boolean;
    "completed": boolean;

    /** Creates a new Chunk instance. */
    constructor($$source: Partial<Chunk> = {}) {
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("start" in $$source)) {
            this["start"] = 0;
        }
        if (!("end" in $$source)) {
            this["end"] = 0;
        }
        if (!("downloaded" in $$source)) {
            this["downloaded"] = 0;
        }
        if (!("assisted" in $$source)) {
            this["assisted"] = false;
        }
        if (!("completed" in $$source)) {
            this["completed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Chunk instance from a string or object.
     */
    static createFrom($$source: any = {}): Chunk {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Chunk($$parsedSource as Partial<Chunk>);
    }
}

/**
 * FailurePhase records which stage of the pipeline failed. 传输与处理是两条不同的失败路径：
 * 传输失败可重新传输，处理失败只能复用已下载分片重试处理（ADR-0001/ADR-0004）。
 * 它属于任务契约，使界面按任务事实选择重试动作，而不是从错误文案推断失败类型。
 */
export enum FailurePhase {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FailurePhaseNone = "",
    FailurePhaseTransfer = "transfer",
    FailurePhaseProcessing = "processing",
};

/**
 * Status represents the download task status.
 */
export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusQueued = "queued",
    StatusDownloading = "downloading",
    StatusProcessing = "processing",
    StatusPaused = "paused",
    StatusCompleted = "completed",
    StatusError = "error",
};

/**
 * Task represents a download task in SheepGet.
 */
export class Task {
    "id": string;
    "url": string;

    /**
     * PageURL 是该下载任务的来源网页地址（如浏览器扩展捕获时所在的源页面）。
     * 当下载链接失效或用户需要时，可直接在浏览器中重新打开该源网页。
     */
    "pageUrl"?: string;
    "filename": string;
    "directory": string;

    /**
     * CategoryID 是该下载任务命中的分类 ID（如 "builtin-video"、"custom-game"）。
     * 在任务创建时由后端的分类规则或文件信息窗口的用户选择判定并固化在任务上，
     * 作为历史归属的单一事实来源，界面直接读取该字段，不再重复推算。
     */
    "categoryId"?: string;
    "tempDir"?: string;
    "totalBytes": number;
    "downloaded": number;

    /**
     * bytes per second
     */
    "speed": number;
    "status": Status;
    "failurePhase"?: FailurePhase;
    "errorMsg"?: string;
    "maxConcurrency": number;
    "resumable": boolean;
    "etag"?: string;
    "lastModified"?: string;

    /**
     * Duration 是媒体文件的时长（秒），0 表示还没识别出来或不是媒体文件。
     * 它在下载完成后由本地文件解析写入：那时文件已经落地，读它不需要任何网络请求。
     */
    "duration"?: number;
    "createdAt": string;
    "updatedAt": string;

    /**
     * Chunks for multi-connection download state
     */
    "chunks"?: Chunk[];

    /**
     * Media 是 HLS 任务选定的媒体来源（清单地址、清晰度、独立音轨、时长、分片数）。
     * 为空表示这是一次普通 HTTP 传输：一次请求得到的就是成品，没有处理阶段。
     * 续传、重试与重启都只靠它重新取回清单，不依赖上一次运行留下的内存状态。
     */
    "media"?: hls$0.Source | null;

    /**
     * SegmentsDone/SegmentsTotal 是 HLS 传输的分片进度，界面据此显示「分片 N/M」。
     * 分片下载是多路并发进行的，但字节数进度条本身看不出这一点；有了这个计数，
     * 「正在并发抓取分片」对用户才是可见的。普通 HTTP 传输两个字段都是 0，界面不显示。
     */
    "segmentsDone"?: number;
    "segmentsTotal"?: number;

    /**
     * SegmentDone 是每个分片的完成状态，索引即分片序号（视频清单在前、音轨清单在后拼接）。
     * 界面据此把进度条画成一格一分片的分段条——和普通 HTTP 的多线程分段同样的视觉，
     * 否则 HLS 只有一根从头到尾的实心条，多路并发完全看不出来。普通 HTTP 传输为空。
     */
    "segmentDone"?: boolean[];

    /**
     * MediaInputs 是本次传输已经落盘、要交给 Media Processor 的输入（分片目录内的文件名）。
     * 传输与处理是两条不同的失败路径（ADR-0004）：有了它，重试处理直接用现成输入，
     * 不必再为取一次清单把网络再走一遍。
     */
    "mediaInputs"?: hls$0.Inputs | null;

    /**
     * TransferDone 表示 MediaInputs 已经全部就绪，剩下的只是处理。
     * 它是「传输已完成」这一事实的唯一记录——处理失败后不能靠重新传输来恢复。
     */
    "transferDone"?: boolean;

    /**
     * RequestHeaders carries request context (Referer, Cookie, Authorization, …) required by
     * links whose authorization has expired; applied to every probe and transfer request.
     * Encapsulated in RequestCredentials to ensure sensitive fields are masked by default on serialization.
     */
    "requestHeaders"?: credentials$0.RequestCredentials;

    /** Creates a new Task instance. */
    constructor($$source: Partial<Task> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("directory" in $$source)) {
            this["directory"] = "";
        }
        if (!("totalBytes" in $$source)) {
            this["totalBytes"] = 0;
        }
        if (!("downloaded" in $$source)) {
            this["downloaded"] = 0;
        }
        if (!("speed" in $$source)) {
            this["speed"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = Status.$zero;
        }
        if (!("maxConcurrency" in $$source)) {
            this["maxConcurrency"] = 0;
        }
        if (!("resumable" in $$source)) {
            this["resumable"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Task instance from a string or object.
     */
    static createFrom($$source: any = {}): Task {
        const $$createField20_0 = $$createType1;
        const $$createField21_0 = $$createType3;
        const $$createField24_0 = $$createType4;
        const $$createField25_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("chunks" in $$parsedSource) {
            $$parsedSource["chunks"] = $$createField20_0($$parsedSource["chunks"]);
        }
        if ("media" in $$parsedSource) {
            $$parsedSource["media"] = $$createField21_0($$parsedSource["media"]);
        }
        if ("segmentDone" in $$parsedSource) {
            $$parsedSource["segmentDone"] = $$createField24_0($$parsedSource["segmentDone"]);
        }
        if ("mediaInputs" in $$parsedSource) {
            $$parsedSource["mediaInputs"] = $$createField25_0($$parsedSource["mediaInputs"]);
        }
        return new Task($$parsedSource as Partial<Task>);
    }
}

// Private type creation functions
const $$createType0 = Chunk.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = hls$0.Source.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = hls$0.Inputs.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
