// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Chunk represents a segment of a file being downloaded.
 */
export class Chunk {
    "index": number;
    "start": number;
    "end": number;
    "downloaded": number;
    "assisted": boolean;
    "completed": boolean;

    /** Creates a new Chunk instance. */
    constructor($$source: Partial<Chunk> = {}) {
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("start" in $$source)) {
            this["start"] = 0;
        }
        if (!("end" in $$source)) {
            this["end"] = 0;
        }
        if (!("downloaded" in $$source)) {
            this["downloaded"] = 0;
        }
        if (!("assisted" in $$source)) {
            this["assisted"] = false;
        }
        if (!("completed" in $$source)) {
            this["completed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Chunk instance from a string or object.
     */
    static createFrom($$source: any = {}): Chunk {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Chunk($$parsedSource as Partial<Chunk>);
    }
}

/**
 * Status represents the download task status.
 */
export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusQueued = "queued",
    StatusDownloading = "downloading",
    StatusPaused = "paused",
    StatusCompleted = "completed",
    StatusError = "error",
};

/**
 * Task represents a download task in SheepGet.
 */
export class Task {
    "id": string;
    "url": string;
    "filename": string;
    "directory": string;
    "totalBytes": number;
    "downloaded": number;

    /**
     * bytes per second
     */
    "speed": number;
    "status": Status;
    "errorMsg"?: string;
    "maxConcurrency": number;
    "resumable": boolean;
    "etag"?: string;
    "lastModified"?: string;
    "createdAt": string;
    "updatedAt": string;

    /**
     * Chunks for multi-connection download state
     */
    "chunks"?: Chunk[];

    /**
     * RequestHeaders carries request context (Referer, Cookie, Authorization, …) required by
     * links whose authorization has expired; applied to every probe and transfer request.
     */
    "requestHeaders"?: { [_ in string]?: string };

    /** Creates a new Task instance. */
    constructor($$source: Partial<Task> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("directory" in $$source)) {
            this["directory"] = "";
        }
        if (!("totalBytes" in $$source)) {
            this["totalBytes"] = 0;
        }
        if (!("downloaded" in $$source)) {
            this["downloaded"] = 0;
        }
        if (!("speed" in $$source)) {
            this["speed"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = Status.$zero;
        }
        if (!("maxConcurrency" in $$source)) {
            this["maxConcurrency"] = 0;
        }
        if (!("resumable" in $$source)) {
            this["resumable"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Task instance from a string or object.
     */
    static createFrom($$source: any = {}): Task {
        const $$createField15_0 = $$createType1;
        const $$createField16_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("chunks" in $$parsedSource) {
            $$parsedSource["chunks"] = $$createField15_0($$parsedSource["chunks"]);
        }
        if ("requestHeaders" in $$parsedSource) {
            $$parsedSource["requestHeaders"] = $$createField16_0($$parsedSource["requestHeaders"]);
        }
        return new Task($$parsedSource as Partial<Task>);
    }
}

// Private type creation functions
const $$createType0 = Chunk.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
