// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as hls$0 from "../hls/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as task$0 from "../task/models.js";

/**
 * CleanupDuplicateGroup represents a group of completed tasks pointing to files with identical size and MD5 hash.
 */
export class CleanupDuplicateGroup {
    "md5": string;
    "fileSize": number;
    "originalTask": task$0.Task | null;
    "duplicateTasks": (task$0.Task | null)[];

    /** Creates a new CleanupDuplicateGroup instance. */
    constructor($$source: Partial<CleanupDuplicateGroup> = {}) {
        if (!("md5" in $$source)) {
            this["md5"] = "";
        }
        if (!("fileSize" in $$source)) {
            this["fileSize"] = 0;
        }
        if (!("originalTask" in $$source)) {
            this["originalTask"] = null;
        }
        if (!("duplicateTasks" in $$source)) {
            this["duplicateTasks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CleanupDuplicateGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): CleanupDuplicateGroup {
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("originalTask" in $$parsedSource) {
            $$parsedSource["originalTask"] = $$createField2_0($$parsedSource["originalTask"]);
        }
        if ("duplicateTasks" in $$parsedSource) {
            $$parsedSource["duplicateTasks"] = $$createField3_0($$parsedSource["duplicateTasks"]);
        }
        return new CleanupDuplicateGroup($$parsedSource as Partial<CleanupDuplicateGroup>);
    }
}

/**
 * CleanupExecuteOptions specifies which cleanable items to delete.
 */
export class CleanupExecuteOptions {
    "deleteOlderTasks": boolean;
    "deleteOlderDiskFiles": boolean;
    "olderThanDays": number;
    "deleteDuplicates": boolean;
    "deleteMissingTasks": boolean;

    /**
     * DeleteOldLogs 删除超过 OlderThanDays 的历史日志文件；正在写入的那一份始终保留。
     */
    "deleteOldLogs": boolean;
    "logDir"?: string;
    "activeLogPath"?: string;

    /** Creates a new CleanupExecuteOptions instance. */
    constructor($$source: Partial<CleanupExecuteOptions> = {}) {
        if (!("deleteOlderTasks" in $$source)) {
            this["deleteOlderTasks"] = false;
        }
        if (!("deleteOlderDiskFiles" in $$source)) {
            this["deleteOlderDiskFiles"] = false;
        }
        if (!("olderThanDays" in $$source)) {
            this["olderThanDays"] = 0;
        }
        if (!("deleteDuplicates" in $$source)) {
            this["deleteDuplicates"] = false;
        }
        if (!("deleteMissingTasks" in $$source)) {
            this["deleteMissingTasks"] = false;
        }
        if (!("deleteOldLogs" in $$source)) {
            this["deleteOldLogs"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CleanupExecuteOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): CleanupExecuteOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CleanupExecuteOptions($$parsedSource as Partial<CleanupExecuteOptions>);
    }
}

/**
 * CleanupExecuteResult returns the summary of the cleanup execution.
 */
export class CleanupExecuteResult {
    "deletedTaskCount": number;
    "deletedFileCount": number;
    "freedBytes": number;
    "errors"?: string[];

    /** Creates a new CleanupExecuteResult instance. */
    constructor($$source: Partial<CleanupExecuteResult> = {}) {
        if (!("deletedTaskCount" in $$source)) {
            this["deletedTaskCount"] = 0;
        }
        if (!("deletedFileCount" in $$source)) {
            this["deletedFileCount"] = 0;
        }
        if (!("freedBytes" in $$source)) {
            this["freedBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CleanupExecuteResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CleanupExecuteResult {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField3_0($$parsedSource["errors"]);
        }
        return new CleanupExecuteResult($$parsedSource as Partial<CleanupExecuteResult>);
    }
}

/**
 * CleanupLogFile 是一个可清理的历史日志文件。
 */
export class CleanupLogFile {
    "path": string;
    "name": string;
    "size": number;
    "modTime": string;

    /** Creates a new CleanupLogFile instance. */
    constructor($$source: Partial<CleanupLogFile> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("modTime" in $$source)) {
            this["modTime"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CleanupLogFile instance from a string or object.
     */
    static createFrom($$source: any = {}): CleanupLogFile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CleanupLogFile($$parsedSource as Partial<CleanupLogFile>);
    }
}

/**
 * CleanupScanOptions specifies filters for scanning cleanable tasks and files.
 */
export class CleanupScanOptions {
    "olderThanDays": number;
    "deleteOlderDiskFiles": boolean;
    "checkDuplicates": boolean;
    "checkMissingFiles": boolean;

    /**
     * CheckOldLogs 打开后才扫描日志文件。LogDir 与 ActiveLogPath 由调用方给出：
     * 引擎不猜数据目录长什么样，但「哪些文件算日志、多旧才算旧」这类规则留在引擎里统一判定。
     */
    "checkOldLogs": boolean;
    "logDir"?: string;
    "activeLogPath"?: string;

    /** Creates a new CleanupScanOptions instance. */
    constructor($$source: Partial<CleanupScanOptions> = {}) {
        if (!("olderThanDays" in $$source)) {
            this["olderThanDays"] = 0;
        }
        if (!("deleteOlderDiskFiles" in $$source)) {
            this["deleteOlderDiskFiles"] = false;
        }
        if (!("checkDuplicates" in $$source)) {
            this["checkDuplicates"] = false;
        }
        if (!("checkMissingFiles" in $$source)) {
            this["checkMissingFiles"] = false;
        }
        if (!("checkOldLogs" in $$source)) {
            this["checkOldLogs"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CleanupScanOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): CleanupScanOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CleanupScanOptions($$parsedSource as Partial<CleanupScanOptions>);
    }
}

/**
 * CleanupScanResult contains the preview results of cleanable items and authoritative totals.
 */
export class CleanupScanResult {
    "olderTasks": (task$0.Task | null)[];
    "olderFilesBytes": number;
    "duplicateGroups": CleanupDuplicateGroup[];
    "duplicateFilesBytes": number;
    "missingTasks": (task$0.Task | null)[];
    "oldLogFiles": CleanupLogFile[];
    "oldLogFilesBytes": number;

    /**
     * TotalCleanableTasks is the deduplicated count of tasks that would be removed.
     */
    "totalCleanableTasks": number;

    /**
     * TotalCleanableFiles is the count of distinct disk files that would be deleted.
     */
    "totalCleanableFiles": number;

    /**
     * TotalFreedBytes is the total disk bytes freed without double-counting.
     */
    "totalFreedBytes": number;

    /** Creates a new CleanupScanResult instance. */
    constructor($$source: Partial<CleanupScanResult> = {}) {
        if (!("olderTasks" in $$source)) {
            this["olderTasks"] = [];
        }
        if (!("olderFilesBytes" in $$source)) {
            this["olderFilesBytes"] = 0;
        }
        if (!("duplicateGroups" in $$source)) {
            this["duplicateGroups"] = [];
        }
        if (!("duplicateFilesBytes" in $$source)) {
            this["duplicateFilesBytes"] = 0;
        }
        if (!("missingTasks" in $$source)) {
            this["missingTasks"] = [];
        }
        if (!("oldLogFiles" in $$source)) {
            this["oldLogFiles"] = [];
        }
        if (!("oldLogFilesBytes" in $$source)) {
            this["oldLogFilesBytes"] = 0;
        }
        if (!("totalCleanableTasks" in $$source)) {
            this["totalCleanableTasks"] = 0;
        }
        if (!("totalCleanableFiles" in $$source)) {
            this["totalCleanableFiles"] = 0;
        }
        if (!("totalFreedBytes" in $$source)) {
            this["totalFreedBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CleanupScanResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CleanupScanResult {
        const $$createField0_0 = $$createType2;
        const $$createField2_0 = $$createType5;
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("olderTasks" in $$parsedSource) {
            $$parsedSource["olderTasks"] = $$createField0_0($$parsedSource["olderTasks"]);
        }
        if ("duplicateGroups" in $$parsedSource) {
            $$parsedSource["duplicateGroups"] = $$createField2_0($$parsedSource["duplicateGroups"]);
        }
        if ("missingTasks" in $$parsedSource) {
            $$parsedSource["missingTasks"] = $$createField4_0($$parsedSource["missingTasks"]);
        }
        if ("oldLogFiles" in $$parsedSource) {
            $$parsedSource["oldLogFiles"] = $$createField5_0($$parsedSource["oldLogFiles"]);
        }
        return new CleanupScanResult($$parsedSource as Partial<CleanupScanResult>);
    }
}

/**
 * HLSProbe 是一条链接的 HLS 事实。
 */
export class HLSProbe {
    "isHls": boolean;

    /**
     * PlaylistURL 是清单地址，原样保留（可能带查询串，取回清单必须与用户给的一致）。
     */
    "playlistUrl"?: string;

    /**
     * Variants 是可选清晰度。只有一项时不构成选择，界面不必弹选择步骤。
     */
    "variants"?: hls$0.Variant[];

    /**
     * Options 是 Variants 的界面形态：展示名只在后端算一次（hls.VariantOptions），
     * 文件信息窗口与扩展悬浮条拿同一份名字，不在前端各算一遍。
     */
    "options"?: hls$0.VariantOption[];

    /**
     * Media 是登记前已经选定的来源。为空表示清晰度还没选——多清晰度时界面先选再进来
     * （Ticket 07：多清晰度在进入信息对话框前选择）。有它时建任务直接采用，不再重新探测。
     */
    "media"?: hls$0.Source | null;

    /** Creates a new HLSProbe instance. */
    constructor($$source: Partial<HLSProbe> = {}) {
        if (!("isHls" in $$source)) {
            this["isHls"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HLSProbe instance from a string or object.
     */
    static createFrom($$source: any = {}): HLSProbe {
        const $$createField2_0 = $$createType9;
        const $$createField3_0 = $$createType11;
        const $$createField4_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("variants" in $$parsedSource) {
            $$parsedSource["variants"] = $$createField2_0($$parsedSource["variants"]);
        }
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField3_0($$parsedSource["options"]);
        }
        if ("media" in $$parsedSource) {
            $$parsedSource["media"] = $$createField4_0($$parsedSource["media"]);
        }
        return new HLSProbe($$parsedSource as Partial<HLSProbe>);
    }
}

/**
 * ProbeResult holds the probed metadata and duplicate-task state for a URL.
 */
export class ProbeResult {
    "url": string;
    "filename": string;
    "totalBytes": number;
    "resumable": boolean;
    "etag": string;
    "lastModified": string;
    "contentType": string;
    "duplicateTask"?: task$0.Task | null;

    /**
     * HLS 是这条链接的 HLS 事实；为空表示它不是清单，按普通文件下载。
     */
    "hls"?: HLSProbe | null;

    /** Creates a new ProbeResult instance. */
    constructor($$source: Partial<ProbeResult> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("totalBytes" in $$source)) {
            this["totalBytes"] = 0;
        }
        if (!("resumable" in $$source)) {
            this["resumable"] = false;
        }
        if (!("etag" in $$source)) {
            this["etag"] = "";
        }
        if (!("lastModified" in $$source)) {
            this["lastModified"] = "";
        }
        if (!("contentType" in $$source)) {
            this["contentType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProbeResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ProbeResult {
        const $$createField7_0 = $$createType1;
        const $$createField8_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("duplicateTask" in $$parsedSource) {
            $$parsedSource["duplicateTask"] = $$createField7_0($$parsedSource["duplicateTask"]);
        }
        if ("hls" in $$parsedSource) {
            $$parsedSource["hls"] = $$createField8_0($$parsedSource["hls"]);
        }
        return new ProbeResult($$parsedSource as Partial<ProbeResult>);
    }
}

// Private type creation functions
const $$createType0 = task$0.Task.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = CleanupDuplicateGroup.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = CleanupLogFile.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = hls$0.Variant.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = hls$0.VariantOption.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = hls$0.Source.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = HLSProbe.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
