// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as task$0 from "../task/models.js";

/**
 * ConsistencyResult reports whether an updated URL is consistent with original task file.
 */
export class ConsistencyResult {
    "consistent": boolean;
    "reason"?: string;
    "totalBytes": number;
    "etag": string;
    "resumable": boolean;

    /** Creates a new ConsistencyResult instance. */
    constructor($$source: Partial<ConsistencyResult> = {}) {
        if (!("consistent" in $$source)) {
            this["consistent"] = false;
        }
        if (!("totalBytes" in $$source)) {
            this["totalBytes"] = 0;
        }
        if (!("etag" in $$source)) {
            this["etag"] = "";
        }
        if (!("resumable" in $$source)) {
            this["resumable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConsistencyResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ConsistencyResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConsistencyResult($$parsedSource as Partial<ConsistencyResult>);
    }
}

/**
 * ProbeResult holds the probed metadata and duplicate-task state for a URL.
 */
export class ProbeResult {
    "url": string;
    "filename": string;
    "totalBytes": number;
    "resumable": boolean;
    "etag": string;
    "lastModified": string;
    "contentType": string;
    "duplicateTask"?: task$0.Task | null;

    /** Creates a new ProbeResult instance. */
    constructor($$source: Partial<ProbeResult> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("totalBytes" in $$source)) {
            this["totalBytes"] = 0;
        }
        if (!("resumable" in $$source)) {
            this["resumable"] = false;
        }
        if (!("etag" in $$source)) {
            this["etag"] = "";
        }
        if (!("lastModified" in $$source)) {
            this["lastModified"] = "";
        }
        if (!("contentType" in $$source)) {
            this["contentType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProbeResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ProbeResult {
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("duplicateTask" in $$parsedSource) {
            $$parsedSource["duplicateTask"] = $$createField7_0($$parsedSource["duplicateTask"]);
        }
        return new ProbeResult($$parsedSource as Partial<ProbeResult>);
    }
}

// Private type creation functions
const $$createType0 = task$0.Task.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
