// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * RequestCredentials wraps HTTP headers containing potentially sensitive credentials.
 * It is a dedicated map type that implements json.Marshaler and fmt.Stringer to ensure
 * default masking on serialization and formatting while maintaining type safety.
 */
export type RequestCredentials = any;
