// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppUpdateResult contains the result of checking for desktop application updates.
 */
export class AppUpdateResult {
    "hasUpdate": boolean;
    "currentVersion": string;
    "latestVersion": string;
    "releaseTitle": string;
    "releaseNotes": string;
    "releaseUrl": string;
    "assetName": string;
    "assetUrl": string;
    "assetSize": number;
    "isPortable": boolean;

    /** Creates a new AppUpdateResult instance. */
    constructor($$source: Partial<AppUpdateResult> = {}) {
        if (!("hasUpdate" in $$source)) {
            this["hasUpdate"] = false;
        }
        if (!("currentVersion" in $$source)) {
            this["currentVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            this["latestVersion"] = "";
        }
        if (!("releaseTitle" in $$source)) {
            this["releaseTitle"] = "";
        }
        if (!("releaseNotes" in $$source)) {
            this["releaseNotes"] = "";
        }
        if (!("releaseUrl" in $$source)) {
            this["releaseUrl"] = "";
        }
        if (!("assetName" in $$source)) {
            this["assetName"] = "";
        }
        if (!("assetUrl" in $$source)) {
            this["assetUrl"] = "";
        }
        if (!("assetSize" in $$source)) {
            this["assetSize"] = 0;
        }
        if (!("isPortable" in $$source)) {
            this["isPortable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppUpdateResult instance from a string or object.
     */
    static createFrom($$source: any = {}): AppUpdateResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppUpdateResult($$parsedSource as Partial<AppUpdateResult>);
    }
}

/**
 * ExtensionUpdateResult contains the result of checking for browser extension updates.
 */
export class ExtensionUpdateResult {
    "hasUpdate": boolean;
    "currentVersion": string;
    "latestVersion": string;
    "releaseTitle": string;
    "releaseNotes": string;
    "assetName": string;
    "assetUrl": string;
    "assetSize": number;

    /** Creates a new ExtensionUpdateResult instance. */
    constructor($$source: Partial<ExtensionUpdateResult> = {}) {
        if (!("hasUpdate" in $$source)) {
            this["hasUpdate"] = false;
        }
        if (!("currentVersion" in $$source)) {
            this["currentVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            this["latestVersion"] = "";
        }
        if (!("releaseTitle" in $$source)) {
            this["releaseTitle"] = "";
        }
        if (!("releaseNotes" in $$source)) {
            this["releaseNotes"] = "";
        }
        if (!("assetName" in $$source)) {
            this["assetName"] = "";
        }
        if (!("assetUrl" in $$source)) {
            this["assetUrl"] = "";
        }
        if (!("assetSize" in $$source)) {
            this["assetSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExtensionUpdateResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ExtensionUpdateResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExtensionUpdateResult($$parsedSource as Partial<ExtensionUpdateResult>);
    }
}
