// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {task} from '../models';

export function AddTask(arg1:string,arg2:string,arg3:string,arg4:number):Promise<task.Task>;

export function DeleteTask(arg1:string,arg2:boolean):Promise<void>;

export function GetDefaultDownloadDir():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListTasks():Promise<Array<task.Task>>;

export function OnTaskUpdated(arg1:task.Task):Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function PauseTask(arg1:string):Promise<void>;

export function ResumeTask(arg1:string):Promise<void>;

export function RetryTask(arg1:string):Promise<void>;
