// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddTask'](arg1, arg2, arg3, arg4);
}

export function DeleteTask(arg1, arg2) {
  return window['go']['main']['App']['DeleteTask'](arg1, arg2);
}

export function GetDefaultDownloadDir() {
  return window['go']['main']['App']['GetDefaultDownloadDir']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function OnTaskUpdated(arg1) {
  return window['go']['main']['App']['OnTaskUpdated'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function PauseTask(arg1) {
  return window['go']['main']['App']['PauseTask'](arg1);
}

export function ResumeTask(arg1) {
  return window['go']['main']['App']['ResumeTask'](arg1);
}

export function RetryTask(arg1) {
  return window['go']['main']['App']['RetryTask'](arg1);
}
