// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as duplicate$0 from "../duplicate/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as task$0 from "../task/models.js";

/**
 * DownloadRequest represents an incoming download request to be displayed in the FileInfo window.
 */
export class DownloadRequest {
    "url": string;
    "headers"?: { [_ in string]?: string };
    "directory"?: string;
    "filename"?: string;
    "maxConn"?: number;
    "preDownload"?: boolean | null;

    /** Creates a new DownloadRequest instance. */
    constructor($$source: Partial<DownloadRequest> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DownloadRequest {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField1_0($$parsedSource["headers"]);
        }
        return new DownloadRequest($$parsedSource as Partial<DownloadRequest>);
    }
}

/**
 * DownloadResponse is the result of enqueuing or dispatching a download request.
 */
export class DownloadResponse {
    "handled": boolean;

    /**
     * "enqueued", "skip_show_completed", etc.
     */
    "action": string;
    "requestId"?: string;
    "taskId"?: string;

    /** Creates a new DownloadResponse instance. */
    constructor($$source: Partial<DownloadResponse> = {}) {
        if (!("handled" in $$source)) {
            this["handled"] = false;
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): DownloadResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadResponse($$parsedSource as Partial<DownloadResponse>);
    }
}

/**
 * FileInfoItem represents a single item waiting in the file info window queue.
 */
export class FileInfoItem {
    "id": string;
    "url": string;
    "filename": string;
    "suggestedFilename": string;
    "directory": string;
    "categoryId"?: string;
    "totalBytes": number;
    "mimeType": string;
    "resumable": boolean;
    "maxConn": number;
    "preDownload": boolean;
    "preDownloadTaskId"?: string;
    "fileConflict": boolean;
    "duplicateTask"?: task$0.Task | null;

    /**
     * DuplicateDecision 是这次重复的裁决结果：界面只渲染它给出的选项与默认项。
     * 策略本身不下发给窗口，避免窗口把它当成第二份规则来源。
     */
    "duplicateDecision": duplicate$0.Decision;
    "queueIndex": number;
    "queueTotal": number;
    "headers"?: { [_ in string]?: string };

    /** Creates a new FileInfoItem instance. */
    constructor($$source: Partial<FileInfoItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("suggestedFilename" in $$source)) {
            this["suggestedFilename"] = "";
        }
        if (!("directory" in $$source)) {
            this["directory"] = "";
        }
        if (!("totalBytes" in $$source)) {
            this["totalBytes"] = 0;
        }
        if (!("mimeType" in $$source)) {
            this["mimeType"] = "";
        }
        if (!("resumable" in $$source)) {
            this["resumable"] = false;
        }
        if (!("maxConn" in $$source)) {
            this["maxConn"] = 0;
        }
        if (!("preDownload" in $$source)) {
            this["preDownload"] = false;
        }
        if (!("fileConflict" in $$source)) {
            this["fileConflict"] = false;
        }
        if (!("duplicateDecision" in $$source)) {
            this["duplicateDecision"] = (new duplicate$0.Decision());
        }
        if (!("queueIndex" in $$source)) {
            this["queueIndex"] = 0;
        }
        if (!("queueTotal" in $$source)) {
            this["queueTotal"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileInfoItem instance from a string or object.
     */
    static createFrom($$source: any = {}): FileInfoItem {
        const $$createField13_0 = $$createType2;
        const $$createField14_0 = $$createType3;
        const $$createField17_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("duplicateTask" in $$parsedSource) {
            $$parsedSource["duplicateTask"] = $$createField13_0($$parsedSource["duplicateTask"]);
        }
        if ("duplicateDecision" in $$parsedSource) {
            $$parsedSource["duplicateDecision"] = $$createField14_0($$parsedSource["duplicateDecision"]);
        }
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField17_0($$parsedSource["headers"]);
        }
        return new FileInfoItem($$parsedSource as Partial<FileInfoItem>);
    }
}

/**
 * FileInfoSubmission represents user confirmation from the FileInfo window.
 */
export class FileInfoSubmission {
    "requestId": string;
    "url": string;
    "filename": string;
    "directory": string;
    "maxConn": number;
    "preDownload": boolean;

    /**
     * Action 是用户为这次重复选定的动作，取自文件信息窗口收到的裁决选项；
     * 为空时由后端按裁决的默认动作执行。
     */
    "action"?: duplicate$0.Action;
    "reuseTaskId"?: string;

    /** Creates a new FileInfoSubmission instance. */
    constructor($$source: Partial<FileInfoSubmission> = {}) {
        if (!("requestId" in $$source)) {
            this["requestId"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("directory" in $$source)) {
            this["directory"] = "";
        }
        if (!("maxConn" in $$source)) {
            this["maxConn"] = 0;
        }
        if (!("preDownload" in $$source)) {
            this["preDownload"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileInfoSubmission instance from a string or object.
     */
    static createFrom($$source: any = {}): FileInfoSubmission {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileInfoSubmission($$parsedSource as Partial<FileInfoSubmission>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = task$0.Task.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = duplicate$0.Decision.createFrom;
